In [2]:
import numpy as np

# Arrays in numpy

# 1D array

a = np.array([1, 2, 3, 4, 5])

print(a)

# 2D array

b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(b)

# 3D array

c = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(c)

# Get the number of dimensions of an array

print(a.ndim)

print(b.ndim)

print(c.ndim)

# Get the shape of an array

print(a.shape)

print(b.shape)

print(c.shape)

# Get the data type of an array

print(a.dtype)

print(b.dtype)

print(c.dtype)

# Get the size of an array

print(a.size)

print(b.size)

print(c.size)

# Get the item size of an array

print(a.itemsize)

print(b.itemsize)

print(c.itemsize)

# Get the total size of an array

print(a.nbytes)

print(b.nbytes)

print(c.nbytes)

# Accessing elements in an array

print(a[0])

print(b[0, 0])

print(c[0, 0, 0])

# Accessing elements in an array using negative indexing

print(a[-1])

print(b[-1, -1])

print(c[-1, -1, -1])


# Vectorized operations

# Addition

x = np.array([1, 2, 3, 4, 5])

y = np.array([6, 7, 8, 9, 10])

print(x + y)

# Subtraction

print(x - y)

# Multiplication

print(x * y)

# Division

print(x / y)

# Dot product

print(np.dot(x, y))

# Broadcasting

# Adding a scalar to an array

print(x + 2)

# Subtracting a scalar from an array

print(x - 2)

# Multiplying an array by a scalar

print(x * 2)

# Dividing an array by a scalar

print(x / 2)

# Universal functions

# Square root


print(np.sqrt(x))

# Exponential

print(np.exp(x))

# Logarithm

print(np.log(x))

# Trigonometric functions

print(np.sin(x))

print(np.cos(x))

print(np.tan(x))

# Aggregation functions

# Sum

print(np.sum(x))

# Minimum

print(np.min(x))

# Maximum

print(np.max(x))

# Mean

print(np.mean(x))

# Median

print(np.median(x))

# Standard deviation

print(np.std(x))

# Indexing and slicing

# 1D array

a = np.array([1, 2, 3, 4, 5])

print(a[0])

print(a[1])

print(a[2])

# 2D array

b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(b[0, 0])

print(b[0, 1])

print(b[0, 2])

# 3D array

c = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(c[0, 0, 0])

print(c[0, 0, 1])

# Logical Operations

# AND

a = np.array([True, False, True, False])

b = np.array([True, True, False, False])

print(np.logical_and(a, b))

# OR

print(np.logical_or(a, b))

# NOT

print(np.logical_not(a))

# XOR

print(np.logical_xor(a, b))

# Comparison Operations

# Equal

a = np.array([1, 2, 3, 4, 5])

b = np.array([1, 2, 3, 4, 5])

print(np.equal(a, b))

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
1
2
3
(5,)
(3, 3)
(2, 2, 3)
int64
int64
int64
5
9
12
8
8
8
40
72
96
1
1
1
5
9
12
